name: ecommerceapplication
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

#--------------Target sdk-------------#
environment:
  sdk: '>=3.3.0 <4.0.0'

#--------------packages-------------#
dependencies:
  flutter:
    sdk: flutter

#-------utility Packages----#
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  url_launcher: ^6.2.5
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.0
  carousel_slider: ^4.2.1

#-------icons Packages----#
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8


#-------State Management----#
  get: ^4.6.6
  get_storage: ^2.1.1


#-------Firebase----#
  firebase_core: ^2.27.2
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2


#-------Product Specific----#
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.0
  connectivity_plus: ^6.0.2
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.6
  cached_network_image: ^3.3.1
  firebase_app_check: ^0.2.2+6




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0





flutter:

  uses-material-design: true

#--------------assets-------------#
  assets:
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/singupandother/
    - assets/icons/categories/
    - assets/images/banner/
    - assets/images/products/
    - assets/images/user/
    - assets/images/rating_users/
    - assets/icons/payment_methods/
    - assets/images/loading_animation/
    - lib/commons/widgets/loaders/
  
#--------------fonts-------------#
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins-Regular.ttf
           weight: 400
         - asset: assets/fonts/Poppins-Italic.ttf
           style: italic
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/Poppins-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 800


  
  
  
